# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 🏠 Home
    url: /
    weight: 10
  - name: 🗂️ Projects
    url: projects/
    weight: 20
  - name: 🐍 Python
    url: /tags/python/
    weight: 30
  - name: 🇬 Go
    url: /tags/go/
    weight: 40
  - name: 💬 Blog
    url: blog/
    weight: 50
