# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 🏠 Home
    url: /
    weight: 10
  - name: 🗂️ Projects
    url: projects/
    weight: 20
  - name: 🚩 CTF
    url: /tags/ctf/
    weight: 30
  - name: 🐞 Bug Bounty
    url: /tags/bug/
    weight: 40
  - name: 📈 Data Science
    url: /tags/datascience/
    weight: 50
  - name: 🧠 Psychology
    url: /tags/psychology/
    weight: 60
  - name: 🧬 Neuroscience
    url: /tags/neuroscience/
    weight: 70
  - name: 💬 Blog
    url: blog/
    weight: 80
